### ISSUE TITLE
api/Player/Hero - 404

### ISSUE THREAD

**Issue by grishrl** [Zemill/heroesprofile-api-public#17]
https://api.heroesprofile.com/api/Player/Hero?mode=json&battletag=Zemill%231940&region=1&api_token=%token%&game_type=Storm League

Returns a 404 error

**Comment by Zemill** [comment]
Accidentally deleted this endpoint, will resolve

/Player/Hero/All   is the correct endpoint

**Comment by Zemill** [comment]
Fixed
