### ISSUE TITLE
Rate limit response headers enhancement

### ISSUE THREAD

**Issue by Astraeus-** [Zemill/heroesprofile-api-public#25]
I was wondering if you're going to be adding either of the following in addition to the current response in the header:
```
X-RateLimit-Reset:
Epoch time (seconds since 00:00:00 UTC on January 1, 1970) at which the rate limit resets
X-RateLimit-Reset-After:
Total time (in seconds) of when the current rate limit bucket will reset.
```

Currently I would have to wait the full 60 seconds when I reach 0 remaining requests and that's sub-optimal when I would want to retrieve a lot of data.

**Comment by Zemill** [comment]
So we built this site on laravel, and I am using their built in rate limiting.  As of yet, I have not been able to find anything related to the extra response headers you are referencing.  I will continue to investigate though.

I am new to laravel, so if you know something, let me know.

**Comment by Astraeus-** [comment]
I don't know which middleware you're using if any, but I did find the following for the [throttleRequests middleware](https://laravel.com/api/5.7/Illuminate/Routing/Middleware/ThrottleRequests.html#method_addHeaders), which appears to be the default Laravel uses.

I assume their optional `$retryAfter` comes down to the same principle as the `Reset-After` that I mentioned.

**Comment by Zemill** [comment]
I am using that middleware, nice find.  So it looks like I will have to create a custom class that extends the base ThrottleRequest class and override the return method to get what you want.

Not too complicated, but going to take a bit to figure out.

Thanks

**Comment by Zemill** [comment]
By default the ThrottleRequests class does not pick up and send the data for retryAfter.  Although there are references to it, it is set equal to null when the value is not sent to the functions getHeader and addHeader.

This is all happening inside the public function handle method of the ThrottleRequests class, specifically the code

      return $this->addHeaders(
          $response, $maxAttempts,
          $this->calculateRemainingAttempts($key, $maxAttempts),
      );

which currently does not send any data for retry.


Overriding this method appears to break the throttler, so still working the issue

**Comment by Zemill** [comment]
Investigated this further and retry-after is returned through the base laravel ThrottleRequests class ONLY after you have hit your limit.

Let me know if this is what you are looking for

**Comment by Astraeus-** [comment]
Looks like it's provided after going over the limit for the first time as the last permitted request that makes you hit your limit does not provide the retry just yet. Thanks for checking it out for me!
