### ISSUE TITLE
.CSV pulls using semi-colon separators - Workarounds&Options

### ISSUE THREAD

**Issue by Blinded04** [Zemill/heroesprofile-api-public#26]
Currently when you call a Comma Separated Value file, each value is separated by a semi-colon.  
Whether or not Excel doesn't recognizes semi-colons or commas as the separators in a .CSV file is (unfortunately) region specific.  So if your Windows region (US English) uses commas as the default, you end up with one long string of text in each row instead of a table when opening the file in excel. 

Currently, the workarounds are:
1) In windows settings, pull up Control Panel / Clock and Region / Region / Change date, time or number formats / Additional Settings - and change the "List Separator" to a semi-colon.
2) Open each export in notepad and find/replace semi-colons with commas.

Clearly the superior open if frequently using API data is (1) - but if you are working often with .CSVs on the same computer with other colleagues from a "comma region" - you are bound to cause some confusion when the files you send are in an unexpected format - so this might not be an option.

Is it feasible (or even possible?) to add an option for the CSV export to return to separated values by comma instead of semi-colon?

**Comment by Blinded04** [comment]
Better solution - Looks like adding the text:

sep=;

in the first line of a CSV file (as the only text in that line) will allow Excel to open the file property regardless of the windows region or default separator.

Is it feasible to add that to CSV exports, or would that interfere with how other CSV editors read the file?

**Comment by Zemill** [comment]
It should be comma separated.  I will look into it.  But ya, any normal reader should be able to split it on a different char.  Google Sheets you can choose what char to split and same with excel.  Regardless, should be comma by default

**Comment by Blinded04** [comment]
I ran into a roadblock - I changed over my default separator to ";" and can open the CSVs in any reader.  But my batch conversion process doesn't want to recognize ; as a valid separator and I can't figure out why - so I'm just getting a single string of text in each line.

Soooo - if you figure out how to change the default separator to commas in the CSV exports, that would be great! Let me know!

As an alternative - if I added the line:
sep=;
at the top of the CSV using notepad, not only can the reader handle the CSV file without changing default separators, but the macro-based batch conversion process I'm using also converts the file seamlessly.

This may actually be a superior option, as it appears some European regions use a semi-colon as the default separator in Windows.  But either would work for my purposes.

**Comment by lifeinabstract** [comment]
Avadriel here, dev with Heroes Profile. The issue with a comma-separated file is that some of the talent descriptions have commas in them, which would break the CSV. I tested adding the =sep; and while I got it to work, when importing to Google Sheets, it threw an error in that cell. 
My plan is to add an additional parameter for the endpoints for this, so that users can choose to pull the CSV with or without the =sep;

**Comment by Blinded04** [comment]
Sounds good!  That will would work for me, Thanks!

(And you mean sep=; correct? not =sep;)?

**Comment by Blinded04** [comment]
I just wanted you to know I figured out a workaround and I am no longer actively waiting on this feature.  You can throw it on the backburner of "maybes" to consider later.

**Comment by Zemill** [comment]
Closing issue unless it causes more issues.  Semi-colon seems to work well due to some returns having commas in them, which requires escaping or some other method to deal with it.

There are ways to work with semi-colon as the separator, so tabling this to work on other issues
