### ISSUE TITLE
NGS: Endpoint for Hero Stats in a Division

### ISSUE THREAD

**Issue by ebshimizu** [Zemill/heroesprofile-api-public#28]
We use to have it set up so that `/NGS/HeroStats/` took a battletag as an optional argument and it would return the entire division stats for that hero if battletag was absent. Is there a `/NGS/Heroes/Stats` endpoint available?

**Comment by Zemill** [comment]
I have fixed this.

The endpoint has changed from NGS/Player/Hero/Stat  to NGS/Hero/Stat

Let me know if you run into any issues
