### ISSUE TITLE
Player/MMR 500 response

### ISSUE THREAD

**Issue by Astraeus-** [Zemill/heroesprofile-api-public#30]
I noticed that when making an invalid request like:
`/api/Player/MMR?api_token={token}&battletag=dthPUNISH3R%231315&region=2`

Where the combination of battletag and region is incorrect, I get a 500 error, instead of a "more useful" response from which I can guess at what's wrong. (E.g: a 404 that there is no data)

**Comment by Zemill** [comment]
Good idea.  I will look into this.  There are a couple of other endpoints throwing this error for similar reasons.  Will update those as the same time

**Comment by Zemill** [comment]
There was logic in the code to account for the error, but the error mode was not entered due to a logic issue earlier on in the code.


The issue had to do with the determination of the blizz_id.  If a battletag and region were provided that did not provide a valid blizz_id, it was not informing the user of this and instead throwing a 500 error.  The correct return can be seen below.

Battletag provided is either invalid, or no games exist in the database for that player

**Comment by Astraeus-** [comment]
Is there a specific reason that the response code is still 200 instead of e.g: a 404? I don't understand why an error/warning message like the above is a 200 response.

It would help a lot in parsing responses, as now if I fail to parse JSON from the response with a 200 status code it could be a parsing error of actual data or trying to parse one of the error responses.

**Comment by Zemill** [comment]
Alright, i've added a 403 response

**Comment by MGatner** [comment]
This is a very old debate, whether HTTP codes should be strictly HTTP codes or should reflect API response status. It’s totally fine to respond 200 (as in, “the HTTP transaction was successful”) and include an error code or message. Also fine to send an HTTP error code if the API failed (though 403 “Forbidden” might not make the most sense). But whichever way it’s handled it should be consistent across all endpoints and documented.

**Comment by Zemill** [comment]
> This is a very old debate, whether HTTP codes should be strictly HTTP codes or should reflect API response status. It’s totally fine to respond 200 (as in, “the HTTP transaction was successful”) and include an error code or message. Also fine to send an HTTP error code if the API failed (though 403 “Forbidden” might not make the most sense). But whichever way it’s handled it should be consistent across all endpoints and documented.

Ya I don't disagree.  The 403 response allowed me to add a custom message into the response without overriding the built-in 404 response.  That is ultimately why I went with 403.

**Comment by Zemill** [comment]
In terms of consistency, I need to go through and add that response to a few other endpoints.

**Comment by MGatner** [comment]
422 is also popular for errors with individual objects. Probably going to be limited by what your framework supports.
