### ISSUE TITLE
Popularity Is Off

### ISSUE THREAD

**Issue by jpmarcotte** [Zemill/heroesprofile-api-public#32]
example: API requests for `Heroes/Stats/` with `group_by_map: true` returned a response that had Valla on Battlefield for Eternity with a value of 3.86, but the website says it's 82%.

Unfortunately I can't provide an exact response because I already used up my very limited requests for the week.

**Comment by Zemill** [comment]
I will look into this and get back to you.  I will reset your calls once I have resolved the discrepancy

**Comment by Zemill** [comment]
Thanks for bringing this to our attention.  This issue has been resolved and your calls have been reset

**Comment by MGatner** [comment]
That’s some quality service!
