### ISSUE TITLE
An endpoint that allows to retrieve replay files by Map, Game Mode and MMR Tier

### ISSUE THREAD

**Issue by pjmagee** [Zemill/heroesprofile-api-public#51]
`MinId/?MinId={minId}&map={map}&mode={mode}&tier={tier}`

Some examples:

Level 1 filters

`MinId/?MinId=490342902&map=Dragon shire` (specific map any replay)
`MinId/?MinId=49034290&tier=Bronze` (specific tier any map or mode)
`MinId/?MinId=49034290&mode=Storm League` (specific mode any map or tier)

Level 2 filters

`MinId/?MinId=490342902&map=Dragon shire&mode=Storm League` (specific map and mode any tier)
`MinId/?MinId=490342902&map=Dragon shire&tier=bronze` (specific map and tier any mode)
`MinId/?MinId=490342902&mode=Storm League&tier=bronze` (specific mode and tier any map)

Level 3 filters

`MinId/?MinId=490342902&map=Dragon shire&mode=Storm League&tier=platinum` (specific map, specific mode and specific tier)

**Comment by Zemill** [comment]
I have added these.

Please reference https://api.heroesprofile.com/docs/1.0/Replay/MinID
