### ISSUE TITLE
CCL Endpoint suggestions

### ISSUE THREAD

**Issue by stuaroo** [Zemill/heroesprofile-api-public#54]
Not sure if you're planning to continue uploading CCL replays for Season 2, but I thought I'd toss a few suggestions here for the CCL endpoints for possible future development:

* add Team name
    * There's no easy way from the API output to determine which team is Team 0 and which is Team 1 for a replayID.  I can sometimes derive it from a player tag, but not always.  It seems to at least stay consistent for all games through a series (e.g. if Wildheart is Team 0 in game 1 they are also Team 0 in game 5)
* add Team first pick/map pick
    * On the website I see first/map pick labeled but can't tell this from API output.  Thought it might correspond to Team 0 or 1, but looking at the first regular season games (replayID 57 and 58) team 0 is Simplicity in both, while first pick in 57 was SIM but first pick in 58 was SSK
* `game_length` seems to be consistently 45-46 seconds longer than VOD/actual game length
	* Ex: replayID=57: API 22:16, [VOD](https://youtu.be/IkSEQfqoBCg?t=2913) 21:31
	* Ex: replayID=91: API 19:57, [VOD](https://youtu.be/izIXh8qRGrc?t=13192) 19:11
	* I recall reading somewhere that total game time from a replay file differs from the game clock, but I thought that number was bigger than 45-46 seconds.  So anyway this might be working as designed, but thought I'd point it out since I noticed and it was a value I was not expecting

**Comment by Zemill** [comment]
We do intend to have season 2 data on the site.

The value is 70 seconds for the game length value versus actual game played value

I have added team name, first pick (0 for team 0 and 1 for team 1.  In some situations it might say -1, and that is there if it failed to pick it up)
