### ISSUE TITLE
Request for additional API features

### ISSUE THREAD

**Issue by SGDean53** [Zemill/heroesprofile-api-public#55]
I wish to request the following categories of data be added to the API:
1 - Matchup Talent Stats
2 - Talent Stats by Map
3 - Composition Stats

Thanks in advance!

**Comment by Zemill** [comment]
I am going to see if I can get to this within the next few weeks.

Questions/Comments

1:  So the trick with this one, is you have 90 heroes.  Each hero has 89 heroes they can play against.  Its some sort of (90 + 89 + 88 + 87 + n) math combinations, and then times 2 for ally data.  This seems like too much data to pull at once, so my approach might be to require you to pull each hero set 1 at a time, but allow enough endpoints to call all of them as many times a week as our other ones.
So something like ((90 + 89 + 88 + 87 + n) x 2 x 7) for basic (seems like way too much....)
2:  We don't currently show data on the website for this specifically.  You can get to it by changing maps when looking at heroes.  We don't generally expose data through the API that isn't also on the website.  So I will have to think about how/whether to do this, and maybe add a page on the website for it as well.
3:  This is equivalent to the data on https://www.heroesprofile.com/Global/Compositions/ right?

**Comment by SGDean53** [comment]
Thanks for the reply,

1: That sounds like a much better solution, I agree entirely.
2: The way I had been finding this data was by filtering the map on the 'Talent Stats' page; maybe the group_by_map parameter seen in other endpoints could be integrated here?
3: Yes, that is the data I was referring to. If this were integrated, it may also benefit from the group_by_map parameter.

**Comment by Zemill** [comment]
I am still working through this, but I have added the group_by_map parameter to the talent details endpoint

**Comment by Zemill** [comment]
I am closing this.  we investigated this and it is not feasible to add something like this without overwhelming our servers
