### ISSUE TITLE
Request - League Tier where MMR is a property

### ISSUE THREAD

**Issue by jared-craig** [Zemill/heroesprofile-api-public#56]
I noticed some endpoints return League Tier and MMR while others sometimes just return MMR.
Would it be possible to add the League Tier property wherever MMR is returned as well?

**Comment by Zemill** [comment]
Ya I see no reason I cant add that.   I will take a look at that later today

**Comment by Zemill** [comment]
@jared-craig Which endpoint specifically are you facing issues with

**Comment by jared-craig** [comment]
The one specific to my needs was Player/Hero/All. I can't remember if there were others as well.

**Comment by Zemill** [comment]
So for that particular set of data, I do not expose the league tier on the websites Player/Hero/All page.  I try not to present more information through the API than you can get through the live site

**Comment by jared-craig** [comment]
Okay. Just seems a little odd because you can sort of get that result if I were to say loop through all the heroes with the Player/MMR/Hero endpoint.
Whatever you decide though, I'm okay with. Thanks!

**Comment by Zemill** [comment]
That is true, but its the same thing on website

**Comment by Zemill** [comment]
This has been added

**Comment by jared-craig** [comment]
Hey Zemill,
Thank you.
I noticed it appears in the json format but not in the csv format.

**Comment by Zemill** [comment]
> Hey Zemill, Thank you. I noticed it appears in the json format but not in the csv format.

Fixed
