### ISSUE TITLE
Request for new endpoint - search player by nickname

### ISSUE THREAD

**Issue by koksztul** [Zemill/heroesprofile-api-public#57]
Can u please add new endpoint to search player only by nickname for example Zemill (withtout battletag). The endpoint will be raturning single player profile if there is found 1 player or return list of players nickname their details like battletag if there are more then one with that. Something similar to your search input on ur website [heroesprofile.com](http://heroesprofile.com/) if i search for player for example on website Zrokowany i will get zrokowany player profile (finds only one). Also if i search for example DragonBlade i get list of profile that match to this nickname: DragonBlade (EU) | 2424 Games Played,
DragonBlade (NA) | 250 Games Played, ... (list of players that match nickname)

**Comment by Zemill** [comment]
We are reviewing this, to see if it is in line with our approach to player privacy, if it is, I will like add it in the next release coming up this next week
