### ISSUE TITLE
same bugs in parsers like had hotslogs....

### ISSUE THREAD

**Issue by mzayarnyuk** [Zemill/heroesprofile-api-public#58]
sample my account 
https://www.heroesprofile.com/Hero/Single/?blizz_id=60330&battletag=maxoptimus&region=2&hero=Sgt.%20Hammer
must be more then 4000 or 5000 already game with sgt;
your bug system show gg;
hotslogs before deaddown had corect values of total games etc;
good part of your data is correct but not all...
very pity...

**Comment by Zemill** [comment]
Do you have a specific issue you are trying to address?  Maybe its a language gap, but I am not understanding fully what you are after

**Comment by Zemill** [comment]
> sample my account https://www.heroesprofile.com/Hero/Single/?blizz_id=60330&battletag=maxoptimus&region=2&hero=Sgt.%20Hammer must be more then 4000 or 5000 already game with sgt; your bug system show gg; hotslogs before deaddown had corect values of total games etc; good part of your data is correct but not all... very pity...

What uploader are you using?  I am guessing you are trying to say not all your games are uploading?

**Comment by Zemill** [comment]
@mzayarnyuk Looking for a response,

Thanks
