### ISSUE TITLE
Draft order information in the api

### ISSUE THREAD

**Issue by markia** [Zemill/heroesprofile-api-public#59]
I would like to request to be able to access the draft order in the api. The same draft order information for draft format games on the website, I would like to have access to this through the api if it's not too much trouble. Thanks!

**Comment by Zemill** [comment]
Ive added this to the Replay/Data endpoint with a tentative push to production in line with upcoming changes for the new season.

Format will be something like


{
	"48635990": {
		"fingerprint": "fcb4d567-0ddb-7552-94bd-dd3b973df749",
		"game_type": "Storm League",
		"game_date": "2023-05-28 19:45:24",
		"game_length": 1102,
		"game_map": "Sky Temple",
		"game_version": "2.55.3.89754",
		"region": 2,
		"draft_order": [{
			"pick_number": 0,
			"type": "0",
			"player_slot": 2,
			"hero": "Anub'arak"
		}, {
			"pick_number": 1,
			"type": "0",
			"player_slot": 1,
			"hero": "Brightwing"
		}, {
			"pick_number": 2,
			"type": "0",
			"player_slot": 2,
			"hero": "Dehaka"
		}, {
			"pick_number": 3,
			"type": "0",
			"player_slot": 1,
			"hero": "Valla"
		}, {
			"pick_number": 4,
			"type": "1",
			"player_slot": 8,
			"hero": "Diablo"
		}, {
			"pick_number": 5,
			"type": "1",
			"player_slot": 2,
			"hero": "Muradin"
		}, {
			"pick_number": 6,
			"type": "1",
			"player_slot": 4,
			"hero": "Qhira"
		}, {
			"pick_number": 7,
			"type": "1",
			"player_slot": 6,
			"hero": "Anduin"
		}, {
			"pick_number": 8,
			"type": "1",
			"player_slot": 9,
			"hero": "Nazeebo"
		}, {
			"pick_number": 9,
			"type": "0",
			"player_slot": 1,
			"hero": "Rexxar"
		}, {
			"pick_number": 10,
			"type": "0",
			"player_slot": 2,
			"hero": "Deathwing"
		}, {
			"pick_number": 11,
			"type": "1",
			"player_slot": 3,
			"hero": "Malfurion"
		}, {
			"pick_number": 12,
			"type": "1",
			"player_slot": 0,
			"hero": "Tychus"
		}, {
			"pick_number": 13,
			"type": "1",
			"player_slot": 5,
			"hero": "Valeera"
		}, {
			"pick_number": 14,
			"type": "1",
			"player_slot": 7,
			"hero": "Sylvanas"
		}, {
			"pick_number": 15,
			"type": "1",
			"player_slot": 1,
			"hero": "Jaina"
		}],
		"Lowskills#21332": {
			"hero": "Jaina",
			"hero_level": 20,
			"mastery_taunt": 2,
			"team": 0,
			"winner": false,
			"blizz_id": 12087871,
			"party": "0",
			"player_mmr": 2733.088287764236,
			"hero_mmr": 2314.244621029432,
			"role_mmr": 2664.429692935212,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Fingers of Frost",
				"4": "Frost Shards",
				"7": "Ice Floes",
				"10": "Summon Water Elemental",
				"13": "Ice Barrier",
				"16": "Numbing Blast",
				"20": "Wintermute"
			},
			"scores": {
				"level": 20,
				"kills": 6,
				"assists": 8,
				"takedowns": 14,
				"deaths": 3,
				"highest_kill_streak": 6,
				"hero_damage": 42177,
				"siege_damage": 99279,
				"structure_damage": 11055,
				"minion_damage": 65314,
				"creep_damage": 16990,
				"summon_damage": 2234,
				"time_cc_enemy_heroes": 0,
				"healing": null,
				"self_healing": 3398,
				"damage_taken": 28485,
				"experience_contribution": 12044,
				"town_kills": 0,
				"time_spent_dead": 75,
				"merc_camp_captures": 2,
				"watch_tower_captures": 1,
				"meta_experience": 76784,
				"protection_allies": 0,
				"silencing_enemies": 0,
				"rooting_enemies": 7,
				"stunning_enemies": 0,
				"clutch_heals": 0,
				"escapes": 0,
				"vengeance": 1,
				"outnumbered_deaths": 2,
				"teamfight_escapes": 0,
				"teamfight_healing": 0,
				"teamfight_damage_taken": 13708,
				"teamfight_hero_damage": 21868,
				"multikill": 3,
				"physical_damage": 11237,
				"spell_damage": 145665,
				"regen_globes": 29,
				"first_to_ten": 0
			}
		},
		"QuirkyOrc#2146739": {
			"hero": "Muradin",
			"hero_level": 20,
			"mastery_taunt": 3,
			"team": 0,
			"winner": false,
			"blizz_id": 13141915,
			"party": "0",
			"player_mmr": 2599.163946946972,
			"hero_mmr": 1910.3188831181044,
			"role_mmr": 2497.908490122852,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Third Wind",
				"4": "Reverberation",
				"7": "Skullcracker",
				"10": "Avatar",
				"13": "Bronzebeard Rage",
				"16": "Dwarf Launch",
				"20": "Unstoppable Force"
			},
			"scores": {
				"level": 20,
				"kills": 3,
				"assists": 12,
				"takedowns": 15,
				"deaths": 3,
				"highest_kill_streak": 6,
				"hero_damage": 24984,
				"siege_damage": 32524,
				"structure_damage": 845,
				"minion_damage": 28844,
				"creep_damage": 15133,
				"summon_damage": 1342,
				"time_cc_enemy_heroes": 0,
				"healing": null,
				"self_healing": 26648,
				"damage_taken": 71367,
				"experience_contribution": 10403,
				"town_kills": 0,
				"time_spent_dead": 105,
				"merc_camp_captures": 2,
				"watch_tower_captures": 6,
				"meta_experience": 76784,
				"protection_allies": 0,
				"silencing_enemies": 0,
				"rooting_enemies": 0,
				"stunning_enemies": 30,
				"clutch_heals": 0,
				"escapes": 1,
				"vengeance": 0,
				"outnumbered_deaths": 2,
				"teamfight_escapes": 0,
				"teamfight_healing": 0,
				"teamfight_damage_taken": 51832,
				"teamfight_hero_damage": 19388,
				"multikill": 4,
				"physical_damage": 34901,
				"spell_damage": 35960,
				"regen_globes": 32,
				"first_to_ten": 0
			}
		},
		"Baumkuh#2481": {
			"hero": "Diablo",
			"hero_level": 16,
			"mastery_taunt": 1,
			"team": 1,
			"winner": true,
			"blizz_id": 2428392,
			"party": "0",
			"player_mmr": 2399.164109761152,
			"hero_mmr": 1967.4055989296896,
			"role_mmr": 2289.587203900252,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Feast on Fear",
				"4": "Sacrificial Soul",
				"7": "Diabolical Momentum",
				"10": "Apocalypse",
				"13": "Devastating Charge",
				"16": "Domination",
				"20": "Hellgate"
			},
			"scores": {
				"level": 21,
				"kills": 2,
				"assists": 8,
				"takedowns": 10,
				"deaths": 5,
				"highest_kill_streak": 2,
				"hero_damage": 19116,
				"siege_damage": 22882,
				"structure_damage": 737,
				"minion_damage": 19506,
				"creep_damage": 28463,
				"summon_damage": 1918,
				"time_cc_enemy_heroes": 0,
				"healing": null,
				"self_healing": 14413,
				"damage_taken": 80891,
				"experience_contribution": 7110,
				"town_kills": 0,
				"time_spent_dead": 125,
				"merc_camp_captures": 6,
				"watch_tower_captures": 3,
				"meta_experience": 82911,
				"protection_allies": 0,
				"silencing_enemies": 0,
				"rooting_enemies": 0,
				"stunning_enemies": 29,
				"clutch_heals": 0,
				"escapes": 2,
				"vengeance": 0,
				"outnumbered_deaths": 3,
				"teamfight_escapes": 1,
				"teamfight_healing": 0,
				"teamfight_damage_taken": 65109,
				"teamfight_hero_damage": 14309,
				"multikill": 1,
				"physical_damage": 37355,
				"spell_damage": 33106,
				"regen_globes": 22,
				"first_to_ten": 1
			}
		},
		"imwithstupid#21756": {
			"hero": "Nazeebo",
			"hero_level": 5,
			"mastery_taunt": 0,
			"team": 1,
			"winner": true,
			"blizz_id": 13530390,
			"party": "0",
			"player_mmr": 2341.59154103878,
			"hero_mmr": 1922.6289065551412,
			"role_mmr": 2139.9955487354414,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Widowmakers",
				"4": "Hexed Crawlers",
				"7": "Spirit of Arachyr",
				"10": "Gargantuan",
				"13": "Superstition",
				"16": "Ring of Poison",
				"20": "Humongoid"
			},
			"scores": {
				"level": 21,
				"kills": 2,
				"assists": 7,
				"takedowns": 9,
				"deaths": 4,
				"highest_kill_streak": 4,
				"hero_damage": 48706,
				"siege_damage": 98657,
				"structure_damage": 25224,
				"minion_damage": 61754,
				"creep_damage": 25082,
				"summon_damage": 6329,
				"time_cc_enemy_heroes": 0,
				"healing": null,
				"self_healing": 5717,
				"damage_taken": 23211,
				"experience_contribution": 13964,
				"town_kills": 2,
				"time_spent_dead": 143,
				"merc_camp_captures": 3,
				"watch_tower_captures": 2,
				"meta_experience": 82911,
				"protection_allies": 0,
				"silencing_enemies": 0,
				"rooting_enemies": 0,
				"stunning_enemies": 0,
				"clutch_heals": 0,
				"escapes": 0,
				"vengeance": 0,
				"outnumbered_deaths": 2,
				"teamfight_escapes": 0,
				"teamfight_healing": 0,
				"teamfight_damage_taken": 13953,
				"teamfight_hero_damage": 19172,
				"multikill": 1,
				"physical_damage": 22104,
				"spell_damage": 145168,
				"regen_globes": 24,
				"first_to_ten": 1
			}
		},
		"MelekTaus#21152": {
			"hero": "Anduin",
			"hero_level": 8,
			"mastery_taunt": 0,
			"team": 1,
			"winner": true,
			"blizz_id": 13566195,
			"party": "0",
			"player_mmr": 2695.3167411184677,
			"hero_mmr": 1991.2198910920672,
			"role_mmr": 2546.367107482268,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Power Word: Shield",
				"4": "Moral Compass",
				"7": "Blessed Recovery",
				"10": "Lightbomb",
				"13": "Speed of the Pious",
				"16": "Holy Nova",
				"20": "Inner Fire"
			},
			"scores": {
				"level": 21,
				"kills": 0,
				"assists": 11,
				"takedowns": 11,
				"deaths": 5,
				"highest_kill_streak": 5,
				"hero_damage": 25210,
				"siege_damage": 17193,
				"structure_damage": 1092,
				"minion_damage": 11741,
				"creep_damage": 15950,
				"summon_damage": 2818,
				"time_cc_enemy_heroes": 0,
				"healing": 54931,
				"self_healing": 14530,
				"damage_taken": 40578,
				"experience_contribution": 4572,
				"town_kills": 1,
				"time_spent_dead": 194,
				"merc_camp_captures": 6,
				"watch_tower_captures": 8,
				"meta_experience": 82911,
				"protection_allies": 4991,
				"silencing_enemies": 0,
				"rooting_enemies": 31,
				"stunning_enemies": 8,
				"clutch_heals": 1,
				"escapes": 1,
				"vengeance": 0,
				"outnumbered_deaths": 1,
				"teamfight_escapes": 0,
				"teamfight_healing": 9203,
				"teamfight_damage_taken": 30159,
				"teamfight_hero_damage": 14982,
				"multikill": 1,
				"physical_damage": 26271,
				"spell_damage": 31910,
				"regen_globes": 21,
				"first_to_ten": 1
			}
		},
		"Occido#21602": {
			"hero": "Sylvanas",
			"hero_level": 20,
			"mastery_taunt": 2,
			"team": 1,
			"winner": true,
			"blizz_id": 8649557,
			"party": "0",
			"player_mmr": 2682.209979520552,
			"hero_mmr": 2653.085916097628,
			"role_mmr": 2680.2997238312837,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Overwhelming Affliction",
				"4": "Unstable Poison",
				"7": "Festering Wounds",
				"10": "Wailing Arrow",
				"13": "Remorseless",
				"16": "Will of the Forsaken",
				"20": "Bolt of the Storm"
			},
			"scores": {
				"level": 21,
				"kills": 5,
				"assists": 7,
				"takedowns": 12,
				"deaths": 3,
				"highest_kill_streak": 8,
				"hero_damage": 55410,
				"siege_damage": 86421,
				"structure_damage": 10219,
				"minion_damage": 66464,
				"creep_damage": 33824,
				"summon_damage": 4165,
				"time_cc_enemy_heroes": 0,
				"healing": null,
				"self_healing": 0,
				"damage_taken": 18894,
				"experience_contribution": 14969,
				"town_kills": 1,
				"time_spent_dead": 106,
				"merc_camp_captures": 3,
				"watch_tower_captures": 2,
				"meta_experience": 82911,
				"protection_allies": 0,
				"silencing_enemies": 22,
				"rooting_enemies": 0,
				"stunning_enemies": 0,
				"clutch_heals": 0,
				"escapes": 0,
				"vengeance": 1,
				"outnumbered_deaths": 2,
				"teamfight_escapes": 0,
				"teamfight_healing": 0,
				"teamfight_damage_taken": 12452,
				"teamfight_hero_damage": 33120,
				"multikill": 1,
				"physical_damage": 63705,
				"spell_damage": 111136,
				"regen_globes": 31,
				"first_to_ten": 1
			}
		},
		"Raga#21724": {
			"hero": "Valeera",
			"hero_level": 20,
			"mastery_taunt": 2,
			"team": 1,
			"winner": true,
			"blizz_id": 13715851,
			"party": "0",
			"player_mmr": 2771.593950600616,
			"hero_mmr": 2756.8453739320603,
			"role_mmr": 2794.9677890236962,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Crippling Poison",
				"4": "Relentless Strikes",
				"7": "Mutilate",
				"10": "Cloak of Shadows",
				"13": "Strangle",
				"16": "Seal Fate",
				"20": "Rupture"
			},
			"scores": {
				"level": 21,
				"kills": 5,
				"assists": 6,
				"takedowns": 11,
				"deaths": 1,
				"highest_kill_streak": 11,
				"hero_damage": 39547,
				"siege_damage": 50212,
				"structure_damage": 5597,
				"minion_damage": 36912,
				"creep_damage": 36586,
				"summon_damage": 2924,
				"time_cc_enemy_heroes": 0,
				"healing": null,
				"self_healing": 0,
				"damage_taken": 27741,
				"experience_contribution": 11293,
				"town_kills": 2,
				"time_spent_dead": 15,
				"merc_camp_captures": 6,
				"watch_tower_captures": 4,
				"meta_experience": 82911,
				"protection_allies": 0,
				"silencing_enemies": 57,
				"rooting_enemies": 0,
				"stunning_enemies": 0,
				"clutch_heals": 0,
				"escapes": 0,
				"vengeance": 1,
				"outnumbered_deaths": 1,
				"teamfight_escapes": 0,
				"teamfight_healing": 0,
				"teamfight_damage_taken": 14983,
				"teamfight_hero_damage": 19592,
				"multikill": 1,
				"physical_damage": 46443,
				"spell_damage": 79366,
				"regen_globes": 21,
				"first_to_ten": 1
			}
		},
		"CHUZI#2732": {
			"hero": "Malfurion",
			"hero_level": 3,
			"mastery_taunt": 0,
			"team": 0,
			"winner": false,
			"blizz_id": 13828655,
			"party": "0",
			"player_mmr": 2213.130664637064,
			"hero_mmr": 1773.2312056808235,
			"role_mmr": 2027.382405819174,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Emerald Dreams",
				"4": "Rejuvenation",
				"7": "Nature's Cure",
				"10": "Twilight Dream",
				"13": "Nature's Swiftness",
				"16": "Nature's Balance",
				"20": "Lifebloom"
			},
			"scores": {
				"level": 20,
				"kills": 0,
				"assists": 15,
				"takedowns": 15,
				"deaths": 1,
				"highest_kill_streak": 12,
				"hero_damage": 19170,
				"siege_damage": 22950,
				"structure_damage": 0,
				"minion_damage": 9358,
				"creep_damage": 3934,
				"summon_damage": 5613,
				"time_cc_enemy_heroes": 0,
				"healing": 74374,
				"self_healing": 0,
				"damage_taken": 29090,
				"experience_contribution": 5787,
				"town_kills": 0,
				"time_spent_dead": 50,
				"merc_camp_captures": 1,
				"watch_tower_captures": 5,
				"meta_experience": 76784,
				"protection_allies": 0,
				"silencing_enemies": 21,
				"rooting_enemies": 30,
				"stunning_enemies": 46,
				"clutch_heals": 3,
				"escapes": 1,
				"vengeance": 0,
				"outnumbered_deaths": 0,
				"teamfight_escapes": 0,
				"teamfight_healing": 13226,
				"teamfight_damage_taken": 16494,
				"teamfight_hero_damage": 9640,
				"multikill": 3,
				"physical_damage": 11206,
				"spell_damage": 33499,
				"regen_globes": 31,
				"first_to_ten": 0
			}
		},
		"cebrotea#2768": {
			"hero": "Tychus",
			"hero_level": 9,
			"mastery_taunt": 0,
			"team": 0,
			"winner": false,
			"blizz_id": 8112482,
			"party": "0",
			"player_mmr": 2640.404702086036,
			"hero_mmr": 1983.4159451036633,
			"role_mmr": 2652.4572284546557,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Quarterback",
				"4": "Master Assassin",
				"7": "Relentless Soldier",
				"10": "Drakken Laser Drill",
				"13": "Spray 'n' Pray",
				"16": "Armor Piercing Rounds",
				"20": "Can Do This All Day"
			},
			"scores": {
				"level": 20,
				"kills": 7,
				"assists": 5,
				"takedowns": 12,
				"deaths": 1,
				"highest_kill_streak": 11,
				"hero_damage": 53898,
				"siege_damage": 60986,
				"structure_damage": 4319,
				"minion_damage": 43030,
				"creep_damage": 9151,
				"summon_damage": 4694,
				"time_cc_enemy_heroes": 0,
				"healing": null,
				"self_healing": 0,
				"damage_taken": 43931,
				"experience_contribution": 12107,
				"town_kills": 0,
				"time_spent_dead": 20,
				"merc_camp_captures": 3,
				"watch_tower_captures": 2,
				"meta_experience": 76784,
				"protection_allies": 0,
				"silencing_enemies": 0,
				"rooting_enemies": 0,
				"stunning_enemies": 0,
				"clutch_heals": 0,
				"escapes": 3,
				"vengeance": 0,
				"outnumbered_deaths": 0,
				"teamfight_escapes": 0,
				"teamfight_healing": 0,
				"teamfight_damage_taken": 18376,
				"teamfight_hero_damage": 30840,
				"multikill": 3,
				"physical_damage": 38123,
				"spell_damage": 83496,
				"regen_globes": 28,
				"first_to_ten": 0
			}
		},
		"\u0412\u0430\u0434\u0438\u043c\u0410\u043d\u0434\u0440\u0435\u0435\u0432#2477": {
			"hero": "Qhira",
			"hero_level": 5,
			"mastery_taunt": 0,
			"team": 0,
			"winner": false,
			"blizz_id": 1875365,
			"party": "0",
			"player_mmr": 2527.496697918892,
			"hero_mmr": 1773.2312056808235,
			"role_mmr": 2047.968739057644,
			"mmr_date_parsed": "2023-05-28 15:45:38",
			"talents": {
				"1": "Fatal Wounds",
				"4": "Upstage",
				"7": "Healmonger",
				"10": "Unrelenting Strikes",
				"13": "Chainsaw",
				"16": "Booming Kick",
				"20": "Silent Killer"
			},
			"scores": {
				"level": 20,
				"kills": 2,
				"assists": 10,
				"takedowns": 12,
				"deaths": 7,
				"highest_kill_streak": 3,
				"hero_damage": 35558,
				"siege_damage": 39921,
				"structure_damage": 2286,
				"minion_damage": 28562,
				"creep_damage": 17947,
				"summon_damage": 3072,
				"time_cc_enemy_heroes": 0,
				"healing": null,
				"self_healing": 5951,
				"damage_taken": 47803,
				"experience_contribution": 7678,
				"town_kills": 0,
				"time_spent_dead": 240,
				"merc_camp_captures": 2,
				"watch_tower_captures": 1,
				"meta_experience": 76784,
				"protection_allies": 0,
				"silencing_enemies": 0,
				"rooting_enemies": 0,
				"stunning_enemies": 13,
				"clutch_heals": 0,
				"escapes": 0,
				"vengeance": 0,
				"outnumbered_deaths": 2,
				"teamfight_escapes": 0,
				"teamfight_healing": 0,
				"teamfight_damage_taken": 37121,
				"teamfight_hero_damage": 22035,
				"multikill": 3,
				"physical_damage": 24401,
				"spell_damage": 67024,
				"regen_globes": 26,
				"first_to_ten": 0
			}
		},
		"experience_breakdown": ""
	}
}

**Comment by Zemill** [comment]
Deployed
