### ISSUE TITLE
Request for Draft Order to be added to NGS Replay Data

### ISSUE THREAD

**Issue by jordantoth** [Zemill/heroesprofile-api-public#61]
The `/Replay/Data` endpoint has Draft Order data contained within the `draft_order` array. However, the NGS version of this endpoint (`/NGS/Replay/Data` ) does not include this array. If it would be a small lift to add that info to the NGS replay endpoint that would be very helpful. Thank you!

**Comment by homeofpoe** [comment]
I agree, this would be quite helpful!

**Comment by Zemill** [comment]
Added
