### ISSUE TITLE
Replays/Min_id is listed under the free API, but requires a subscription 

### ISSUE THREAD

**Issue by homeofpoe** [Zemill/heroesprofile-api-public#64]
Min_id is part of the "Replays General" category:

![Screenshot_20240606-123538.png](https://github.com/Heroes-Profile/heroesprofile-api-public/assets/1144217/198f9b78-0519-4b73-88c7-dfd03dfeb987)

The subscription page states "Replays General" are free:

![Screenshot_20240606-123510.png](https://github.com/Heroes-Profile/heroesprofile-api-public/assets/1144217/07e914ea-bcd2-49c9-bcac-7f3a888ec9d2)

Attempting to make a call using the code suggested by [the test client](https://api.heroesprofile.com/endpoints)
results in the following message: 

`No subscription plan chosen`

**Comment by Zemill** [comment]
You need to run it through the openAPI calls

https://api.heroesprofile.com/openApi/Replay/Min_id?min_id=25001668

instead of

https://api.heroesprofile.com/api/Replay/Min_id?min_id=25001668

**Comment by homeofpoe** [comment]
Thank you!  I didn't realize the test client didn't account for that.  Much appreciated.

**Comment by Zemill** [comment]
> Thank you!  I didn't realize the test client didn't account for that.  Much appreciated. 

If you go to the free api page the test client there does

**Comment by homeofpoe** [comment]
Thank you very much! 

For posterity if anyone ends up having the same question, for posterity, here if the separate page: https://api.heroesprofile.com/openAPI
