### ISSUE TITLE
Menu doesn't change after subscribing

### ISSUE THREAD

**Issue by lifeinabstract** [Zemill/heroesprofile-api-public#7]
After making payment for a subscription for the first time, the menus do not reload, so you can't get to any of the navigation items.
Steps to recreate:
1. Create a new account & verify email
2. Choose a subscription and make payment. In the modal window, click "close"
Result: Links for "Api", "Endpoints", etc don't show in the menu. Invoices don't show up. 

Resolution:
* On press of the "close" button, redirect to the "api" page or dashboard page, and reload the Vue menu elements.

**Comment by Zemill** [comment]
Fixed
